// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAKJzxm5krKk4Z_8t33r1RfeioAjuF8fA',
    appId: '1:120395968771:web:30720c3913241f507af936',
    messagingSenderId: '120395968771',
    projectId: 'flutter-app-37dd1',
    authDomain: 'flutter-app-37dd1.firebaseapp.com',
    storageBucket: 'flutter-app-37dd1.appspot.com',
    measurementId: 'G-VYY861LX5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuG038TG60Um9OajuHPY2UQZCLD21Ia5A',
    appId: '1:120395968771:android:99dbea0e2e94d1677af936',
    messagingSenderId: '120395968771',
    projectId: 'flutter-app-37dd1',
    storageBucket: 'flutter-app-37dd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4E62WmIFkLub3If1AIgkQqn8cNy56Jvk',
    appId: '1:120395968771:ios:e1bacf66aac0c3017af936',
    messagingSenderId: '120395968771',
    projectId: 'flutter-app-37dd1',
    storageBucket: 'flutter-app-37dd1.appspot.com',
    iosClientId: '120395968771-qseaah199o2gra65hcug2s7nptpmfrhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4E62WmIFkLub3If1AIgkQqn8cNy56Jvk',
    appId: '1:120395968771:ios:e1bacf66aac0c3017af936',
    messagingSenderId: '120395968771',
    projectId: 'flutter-app-37dd1',
    storageBucket: 'flutter-app-37dd1.appspot.com',
    iosClientId: '120395968771-qseaah199o2gra65hcug2s7nptpmfrhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupProject',
  );
}
